openapi: 3.0.0
info:
  title: hcloud - Auditor
  description: Auditor manages audit logs
  version: 1.0.0
  contact:
    name: MoovIT Software Products GmbH
    url: https://www.moovit-sp.com
    email: info@moovit-sp.com
servers:
  - url: https://eu-central-1.helmut.cloud/api/auditor
    description: EU-Central production server
  - url: https://na-west-1.helmut.cloud/api/auditor
    description: NA-West production server
  - url: https://eu-dev-1.app.helmut.cloud/api/auditor
    description: EU development server
  - url: http://localhost/api/auditor
    description: Localhost
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    patAuth:
      type: http
      scheme: bearer
      bearerFormat: PAT
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CustomError:
      type: object
      properties:
        error:
          type: string
          description: Error name
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
      required:
        - error
        - code
        - message
      description: API errors obey this shape
    Event:
      type: string
      enum:
        - login
        - logout
        - user
        - organization
        - organizationMember
        - team
        - space
        - event
        - stream
        - mail
        - webhook
        - cronjob
        - secret
        - agent
        - avatar
        - serviceAccount
        - database
        - document
        - asset
        - share
        - role
        - group
        - app
      description: Event of the log (login, logout, user, stream, ...)
      example: webhook
    Level:
      type: string
      enum:
        - info
        - warn
        - error
        - debug
      description: Level of the log (info, warn, error, debug, ...)
      example: error
    Origin:
      type: string
      enum:
        - idp
        - high5
        - auditor
        - mailer
        - fuse
        - mothership
        - dali
        - cosmo
      description: Origin of the log (idp, high5, auditor, ...)
      example: mailer
    Type:
      type: string
      enum:
        - read
        - write
        - create
        - update
        - delete
        - execute
        - connect
        - disconnect
        - add
        - remove
        - send
        - receive
      description: Type of the log (read, write, update, ...)
      example: execute
    LicenseTier:
      type: string
      enum:
        - FREE
        - PRO
        - ENTERPRISE
      description: Tier of the license
      example: PRO
    AuditLogDtoWithOrgName:
      type: object
      properties:
        _id:
          type: string
          format: hexadecimal
          description: Unique identifier of this log
          example: 527d1df208337bc792b55f73
        origin:
          $ref: '#/components/schemas/Origin'
        level:
          $ref: '#/components/schemas/Level'
        organizationName:
          type: string
          description: Name of the Organization the log belongs to
        space:
          type: string
          description: Name of the Space
        event:
          $ref: '#/components/schemas/Event'
        user:
          type: string
          description: Name of the user that triggered the audit log
        type:
          $ref: '#/components/schemas/Type'
        timestamp:
          type: number
          minimum: 0
          description: Timestamp in unix format
        message:
          nullable: true
          description: Actual message of the log
        correlationId:
          type: string
          description: Request correlation id
        requestorIp:
          type: string
          description: Ip of the client of the initial request
        assetId:
          type: string
          format: hexadecimal
          description: >-
            Optional asset Id that is just present for events around assets
            (e.g. asset add, comment add to asset, ...)
      required:
        - _id
        - origin
        - level
        - organizationName
        - event
        - user
        - timestamp
        - correlationId
        - requestorIp
      description: Audit log record with organization name
  parameters: {}
paths:
  /v1/org/{orgName}/logs/search:
    post:
      security:
        - bearerAuth:
            - idp:organization:read
        - basicAuth:
            - idp:organization:read
        - patAuth:
            - idp:organization:read
      summary: >-
        Retrieves all audit logs that match the provided search filter, returns
        all audit logs of the organization if no search filter is provided
      tags:
        - AuditLogs
      parameters:
        - schema:
            anyOf:
              - type: string
                minLength: 3
                maxLength: 64
                pattern: ^(?!-)(?!.*--)[a-zA-Z0-9-.]{3,64}(?<!-)$
                description: >-
                  Name of the organization (only alphanumeric characters,
                  hyphens and dots are allowed; it should contain between 3 and
                  64 characters)
                example: MoovIT-Software-Products-GmbH
              - type: string
                minLength: 3
                maxLength: 255
                pattern: ^[\w-+@.]{3,255}$
                description: >-
                  Name of the user's private organization, allowed everything
                  defined in the RFC for the email specification (it should
                  contain between 3 and 255 characters)
                example: hmc@helmut.cloud
          required: true
          name: orgName
          in: path
        - schema:
            type: number
            minimum: 1
            maximum: 100
            default: 25
            description: Page size
          required: false
          name: limit
          in: query
        - schema:
            type: number
            nullable: true
            minimum: 0
            default: 0
            description: Page index
          required: false
          name: page
          in: query
        - schema:
            type: string
          required: true
          name: authorization
          in: header
      responses:
        '200':
          description: List of audit logs that match the search filter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuditLogDtoWithOrgName'
        '400':
          description: >-
            Failed to validate 'path' parameter 'orgName' | Failed to validate
            'query' parameter 'limit' | Failed to validate 'query' parameter
            'page'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomError'
              examples:
                Failed to validate 'path' parameter 'orgName':
                  summary: Failed to validate 'path' parameter 'orgName'
                  description: Failed to validate 'path' parameter 'orgName' - {error}
                  value:
                    code: 004.000.0003
                    error: invalid.parameter
                    message: Failed to validate 'path' parameter 'orgName' - {error}
                Failed to validate 'query' parameter 'limit':
                  summary: Failed to validate 'query' parameter 'limit'
                  description: Failed to validate 'query' parameter 'limit' - {error}
                  value:
                    code: 004.000.0003
                    error: invalid.parameter
                    message: Failed to validate 'query' parameter 'limit' - {error}
                Failed to validate 'query' parameter 'page':
                  summary: Failed to validate 'query' parameter 'page'
                  description: Failed to validate 'query' parameter 'page' - {error}
                  value:
                    code: 004.000.0003
                    error: invalid.parameter
                    message: Failed to validate 'query' parameter 'page' - {error}
        '401':
          description: >-
            You're not authorized | Expected an authentication token that has
            not been provided | Your authentication token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomError'
              examples:
                You're not authorized:
                  summary: You're not authorized
                  value:
                    code: 004.001.0001
                    error: unauthorized
                    message: You're not authorized
                Expected an authentication token that has not been provided:
                  summary: Expected an authentication token that has not been provided
                  value:
                    code: 004.001.0002
                    error: missing.auth.token
                    message: >-
                      Expected an authentication token that has not been
                      provided
                Your authentication token is invalid:
                  summary: Your authentication token is invalid
                  value:
                    code: 004.001.0003
                    error: wrong.auth.token
                    message: Your authentication token is invalid
        '403':
          description: >-
            Required scopes ['idp:organization:read'] not included in
            authorization | User's organization role is insufficient. Must be at
            least ADMIN
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomError'
              examples:
                Required scopes ['idp:organization:read'] not included in authorization:
                  summary: >-
                    Required scopes ['idp:organization:read'] not included in
                    authorization
                  value:
                    code: 004.001.0004
                    error: insufficient.rights
                    message: >-
                      You have not enough rights to access/manipulate this
                      resource
                User's organization role is insufficient. Must be at least ADMIN:
                  summary: >-
                    User's organization role is insufficient. Must be at least
                    ADMIN
                  value:
                    code: 004.001.0004
                    error: insufficient.rights
                    message: >-
                      You have not enough rights to access/manipulate this
                      resource
        '404':
          description: Organization not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomError'
              examples:
                Organization not found:
                  summary: Organization not found
                  value:
                    code: 004.007.0001
                    error: organization.not.found
                    message: Organization not found
        '500':
          description: something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomError'
              examples:
                something went wrong:
                  summary: something went wrong
                  value:
                    code: 004.000.0002
                    error: internal.server.error
                    message: something went wrong
